import Head from "next/head";
import { Inter } from "next/font/google";
import BuiltWith from "@/components/BuiltWith";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Alberto Perez Portfolio</title>
        <meta
          name="description"
          content="Alberto Perez Portfolio website generated by create next app"
          key="desc"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Header />
          <BuiltWith />
        </div>

        <div className={styles.center}>
          {/* <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
        </div>

        <Footer />
      </main>
    </>
  );
}
